### ISSUE TITLE
Plans to support asynchronous javascript?

### ISSUE THREAD

**Issue by ariutta** [doloopwhile/PyExecJS#20]
Any plans to add support for asynchronous javascript? There's a Ruby project, [ExecJS Async](https://github.com/ericallam/execjs-async), that does this with Node.js:

"ExecJS lets you run JavaScript code from Ruby. ExecJS Async allows you to execute, and receive results from, asynchronous javascript."

Thanks!

**Comment by doloopwhile** [comment]
I do not have any plan. But, I will accept pull-requests of the feature.
