### ISSUE TITLE
Make it possible to `require` external libraries.

### ISSUE THREAD

**Issue by doloopwhile** [doloopwhile/PyExecJS#22]
Currently, one can not `require` external libraries in JS script.

Example: https://gist.github.com/brandonwoo/823856a82145c9c76f8b

One of solution is adding parameter of directory to `execjs.exec_` and other methods.
However, the solution depends spec of `nodejs`.

Where should be specify working directory? (or not specify working directory).

**Comment by brandonwoo** [comment]
Hi, maybe you can share your thoughts or outline on how you think this should be implemented?

**Comment by brandonwoo** [comment]
i presume we would use a using a global env if it exists (e.g. EXECJS_NODE_MODULES_PATHS) and adjusting the execution code accordingly? such that

    cmd = self._binary() + [filename]
    
->

    cmd = "NODE_PATH="+modules_path self._binary() + [filename]

if modules_path (EXECJS_NODE_MODULES_PATHS) is specified

**Comment by brandonwoo** [comment]
opened a new pull requesthttps://github.com/doloopwhile/PyExecJS/pull/23
this uses EXECJS_NODE_PATH to specify a custom node path

example usage here https://gist.github.com/brandonwoo/aa4f50b6674f2b7d6935

**Comment by doloopwhile** [comment]
I added `cwd` parameter
https://github.com/doloopwhile/PyExecJS/pull/40
