### ISSUE TITLE
PyExecJS and Web Sockets

### ISSUE THREAD

**Issue by DenisDollfus** [doloopwhile/PyExecJS#30]
Hi,

Is it possible to use PyExecJS to load some JS that initiates a Web Socket connection and then asynchronously calls back from JS to Python? 

As per another question about async JavaScript I assume it's not possible today. Do you confirm?

Thanks.

**Comment by doloopwhile** [comment]
Hello.
Unfortunately, It is impossible to use Web Socket via PyExecJS currently.

Thanks.
