### ISSUE TITLE
Use Js2Py as a fallback

### ISSUE THREAD

**Issue by sametmax** [doloopwhile/PyExecJS#34]
When no native JS VM is available, it's better than nothing to use a pure Python implementation: https://github.com/PiotrDabkowski/Js2Py

**Comment by doloopwhile** [comment]
I do not think that falling back to Js2Py is inconsistent with the use cases of PyExecJS.

One use case of PyExecJS is to execute JS with NodeJS.
There, falling back to Js2Py is useless.

The other use case of PyExecJS is to execute JS program without platform specific problems.
It is not important for me whether VM is native or non-native.
So, if Js2Py worked well as a fallback, I am able to use Js2Py as a primary.

So, I would not to use Js2Py as a fallback now.

**Comment by sametmax** [comment]
The idea is: in places you cannot (or don't want to) installed a compiled dependancy, you will be happy to be using PyExecJS and see it working anyway. But then if you move your code to a place you can install say, nodeJS, then you can enjoy the speed boost without any changes to your code. PyExecJS is the abstraction.

It's the same than using an ORM, and having it capable of running SQLite and Postgres. Yes, if you can have PostGres installed, it's better. But if it's your dev setup or if you are running on a raspberry py, or if you are on a machine with no admin privileges, having sqlite as a fallback is great.

**Comment by doloopwhile** [comment]
I do not have enough time to implement Js2Py runtime. I am awaiting for your pull request.
