### ISSUE TITLE
PyQt5 as Backend

### ISSUE THREAD

**Issue by juancarlospaco** [doloopwhile/PyExecJS#35]
- Add Python3 Qt5 via PyQt5 as Backend.

Basic example (pseudo-code):
```python
QWebView().page().mainFrame().evaluateJavaScript("console.log(42)")
```

:octocat:

**Comment by doloopwhile** [comment]
Please create a pull-request.

**Comment by doloopwhile** [comment]
I do not think PyQt5 support is useful.

It is because PyQt5 is rarely installed in developper's machine.
And, Qt require to instantiate singleton `Application`, so it looks dificult to correctly implement PyQt5 runtime.
