### ISSUE TITLE
Send messages back to python.

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [doloopwhile/PyExecJS#58]
Is it possible to receive messages from the js script like python-shell can https://github.com/extrabacon/python-shell?
It would be very helpful for debugging.

**Comment by doloopwhile** [comment]
@BebeSparkelSparkel
No. It is currently impossible to call Python function from JS script.

It is because PyExecJS have to support various JS runtimes.

It looks difficult for me to implement the feature with Windows JScript.

**Comment by BebeSparkelSparkel** [comment]
Alright, thanks
