### ISSUE TITLE
Cannot use custom node.js modules

### ISSUE THREAD

**Issue by hiviah** [doloopwhile/PyExecJS#59]
Hope I am not overlooking something, but whenever I use "require" for some custom installed nodejs module, I get an exception `execjs._exceptions.ProgramError: Error: Cannot find module`. Is it for instance necessary to set paths somehow where modules would be searched?

Simple test case with one module, [fastrpc](https://github.com/seznam/node-fastrpc):

Install the module `npm install fastrpc`

Try this python code to invoke pyexecjs to invoke the module:

```
#!/usr/bin/env python
import execjs
print "Engine name", execjs.get().name

code = """
var fastrpc = require('fastrpc');

function frpc2json(string) {
    var buffer = new Buffer(string, 'base64');
    var bufferArray = new Uint8Array(buffer);
    var decoded = fastrpc.parse(bufferArray);
    return  JSON.stringify(decoded);
}
"""

ctx = execjs.compile(code)
res = ctx.call("frpc2json", 'yhECAWgRdXNlci5saXN0TWVzc2FnZXM7L1wfASAMbGFiZWwtaWQ6MjU4QAA4ZA==')
print res
```

Result:

```
Engine name Node.js (V8)
Traceback (most recent call last):
  File "./cant_resolve_modules.py", line 17, in <module>
    res = ctx.call("frpc2json", 'yhECAWgRdXNlci5saXN0TWVzc2FnZXM7L1wfASAMbGFiZWwtaWQ6MjU4QAA4ZA==')
  File "/home/ondro/.local/lib/python2.7/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/home/ondro/.local/lib/python2.7/site-packages/execjs/_external_runtime.py", line 87, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/home/ondro/.local/lib/python2.7/site-packages/execjs/_external_runtime.py", line 73, in _eval
    return self.exec_(code)
  File "/home/ondro/.local/lib/python2.7/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/home/ondro/.local/lib/python2.7/site-packages/execjs/_external_runtime.py", line 83, in _exec_
    return self._extract_result(output)
  File "/home/ondro/.local/lib/python2.7/site-packages/execjs/_external_runtime.py", line 165, in _extract_result
    raise exceptions.ProgramError(value)
execjs._exceptions.ProgramError: Error: Cannot find module 'fastrpc'
```

**Comment by tedmiston** [comment]
I came here looking for the same.  I'm thinking I'll probably end up using subprocess in Python to run npm commands directly.  What did you end up doing?

**Comment by hiviah** [comment]
I did a dirty workaround and basically pasted the module in the code if I remember correctly. It worked, but it was a hack.

**Comment by tedmiston** [comment]
I saw a related issue and PR that makes it looks like this may be possible in the current implementation by passing `cwd` or modifying the `NODE_PATH` env var.

https://github.com/doloopwhile/PyExecJS/issues/22

https://github.com/doloopwhile/PyExecJS/pull/23

**Comment by overfl0** [comment]
Hey! I stumbled upon the exact same issue and ended up here as well.
In my case, after tinkering with the code, I realized that nodeenv was setting `env['NODE_PATH']` to a wrong (nonexistent) directory.

After manually fixing that environmental variable, I was able to successfully `require()` a library that I've fetched with npm. You may want to double-check your `NODE_PATH` variable points to the right place and try again.
