### ISSUE TITLE
How do I include pyexecjs in a secure way?

### ISSUE THREAD

**Issue by dmr** [doloopwhile/PyExecJS#61]
I'm new to pyexecjs and want to use it to allow small user scripts.

Right now I can use all the things my node environment offers me, i.e.

```
import execjs
ctx = execjs.compile("const fs = require('fs'); const insecure = () => fs.readdirSync('.');");
ctx.call("insecure")
```

Is there a way to "sandbox" the node environment and only allow certain things?

Thank you for this project, it has been a pleasure to use so far :)

**Comment by doloopwhile** [comment]
No. PyExecJS provide only a functionality of "execute JavaScript".
It does not privide functionalities depends on individual runtime.

**Comment by dmr** [comment]
Thanks for clarification

**Comment by eight04** [comment]
If you use Node.js, try [node_vm2](https://pypi.python.org/pypi/node-vm2).

**Comment by dmr** [comment]
Thank you for the hint, this looks promising
