### ISSUE TITLE
Upgrade/unpin six

### ISSUE THREAD

**Issue by href** [doloopwhile/PyExecJS#66]
[Six](https://pypi.python.org/pypi/six) released a new version (`1.11.0`). PyExecJS's version is pinned to the previous version (`1.10.0`). Is there a reason why it is pinned to this exact version?

As a result this package is incompatible with any package that requires a six version greater than `1.10.0`.

Would it be possible to change the pin to something more forgiving, like `six>=1.10.0`?

**Comment by doloopwhile** [comment]
Understand.
